/**
 * This package contains parser classes that are automatically generated by <i>ANTLR</i>. No other classes should be added here
 * and existing classes should not be edited. Changes to the parser implementation should always be made in the <i>ANTLR</i>
 * grammar file instead. 
 *  
 * @author Ben Stöver
 * @author Charlotte Schmitt
 */
package info.bioinfweb.jtreess.parser;